"""Editable annotation document for the screen overlay."""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass, field
from math import hypot
import pickle
import sys


Point = tuple[float, float]


@dataclass
class TextStyle:
    family: str = "Segoe UI"
    size: float = 20.0
    bold: bool = False
    italic: bool = False
    underline: bool = False
    strike: bool = False
    align: str = "left"
    opacity: float = 1.0
    background: str = ""
    line_spacing: int = 120
    letter_spacing: float = 0.0


@dataclass
class Mark:
    kind: str
    points: list[Point] = field(default_factory=list)
    color: str = "#ff4655"
    width: float = 4.0
    text: str = ""
    text_style: TextStyle | None = None
    text_box: tuple[float, float] | None = None
    opacity: float = 1.0
    image_id: str = ''
    image_size: tuple[float, float] = (0, 0)
    rotation: float = 0.0
    flip_x: bool = False
    flip_y: bool = False
    crop: tuple[float, float, float, float] = (0, 0, 1, 1)
    neon: bool = False

    def moved(self, dx: float, dy: float) -> "Mark":
        result = deepcopy(self)
        result.points = [(x + dx, y + dy) for x, y in self.points]
        return result

    def bounds(self) -> tuple[float, float, float, float]:
        if self.kind == 'image':
            from image_capture import image_path
            r = image_path(self).boundingRect()
            return r.left(), r.top(), r.right(), r.bottom()
        if not self.points:
            return (0, 0, 0, 0)
        xs, ys = zip(*self.points)
        extra = max(self.width, 8) + (18 if self.neon and self.kind == 'pen' else 0)
        if self.kind == "text":
            if self.text_box:
                return (xs[0], ys[0], xs[0] + self.text_box[0], ys[0] + self.text_box[1])
            lines = self.text.splitlines() or [""]
            return (xs[0], ys[0] - self.width * 6,
                    xs[0] + max(map(len, lines)) * self.width * 4.5,
                    ys[0] + (len(lines) - 1) * self.width * 8)
        return (min(xs) - extra, min(ys) - extra,
                max(xs) + extra, max(ys) + extra)

    def hit(self, x: float, y: float) -> bool:
        if self.kind == 'image':
            from image_capture import image_path
            from PySide6.QtCore import QPointF
            return image_path(self).contains(QPointF(x,y))
        left, top, right, bottom = self.bounds()
        if not (left - 6 <= x <= right + 6 and top - 6 <= y <= bottom + 6):
            return False
        if self.kind in ("pen", "line", "arrow") and len(self.points) >= 2:
            if self.kind == 'pen' and self.neon:
                from pen_effects import smooth_path
                from PySide6.QtGui import QPainterPathStroker
                from PySide6.QtCore import QPointF, Qt
                stroker=QPainterPathStroker()
                stroker.setWidth(max(18,2*(self.width+4)))
                stroker.setCapStyle(Qt.RoundCap);stroker.setJoinStyle(Qt.RoundJoin)
                return stroker.createStroke(smooth_path(self.points)).contains(QPointF(x,y))
            for a, b in zip(self.points, self.points[1:]):
                vx, vy = b[0] - a[0], b[1] - a[1]
                length2 = vx * vx + vy * vy
                t = max(0, min(1, ((x-a[0])*vx + (y-a[1])*vy) / length2)) if length2 else 0
                if hypot(x - a[0] - t*vx, y - a[1] - t*vy) <= max(9, self.width + 4):
                    return True
            return False
        return True


class Document:
    def __init__(self) -> None:
        self.marks: list[Mark] = []
        self._undo: list[tuple[bytes, ...]] = []
        self._redo: list[tuple[bytes, ...]] = []
        self._history_pool: dict[bytes, bytes] = {}
        self._image_refs: dict[bytes, str] = {}
        self.history_budget = 32 * 1024 * 1024
        self.clipboard: list[Mark] = []

    def checkpoint(self) -> None:
        self._undo.append(self._snapshot())
        self._undo = self._undo[-100:]
        self._redo.clear()
        self._trim_history()

    def _snapshot(self):
        # Immutable serialized records share unchanged strokes across history.
        # Only internally generated bytes are deserialized; no pickle file input.
        result = []
        for mark in self.marks:
            payload = pickle.dumps(mark, protocol=5)
            result.append(self._history_pool.setdefault(payload, payload))
            if mark.image_id:
                self._image_refs[payload] = mark.image_id
        return tuple(result)

    def _trim_history(self):
        while True:
            used = {record for state in self._undo + self._redo for record in state}
            self._history_pool = {record: record for record in used}
            self._image_refs = {record: value for record,value in self._image_refs.items() if record in used}
            self.history_bytes = (sum(sys.getsizeof(record) for record in used)
                                  + sum(sys.getsizeof(state) for state in self._undo + self._redo)
                                  + sys.getsizeof(self._history_pool))
            if self.history_bytes <= self.history_budget or not (self._undo or self._redo):
                break
            # Oldest undo / farthest future redo is least useful under pressure.
            (self._undo if self._undo else self._redo).pop(0)

    def undo(self) -> bool:
        if not self._undo:
            return False
        state = self._undo.pop()
        self._redo.append(self._snapshot())
        self.marks = [pickle.loads(record) for record in state]
        self._trim_history()
        return True

    def redo(self) -> bool:
        if not self._redo:
            return False
        state = self._redo.pop()
        self._undo.append(self._snapshot())
        self.marks = [pickle.loads(record) for record in state]
        self._trim_history()
        return True

    def hit(self, x: float, y: float) -> int | None:
        for index in range(len(self.marks) - 1, -1, -1):
            if self.marks[index].hit(x, y):
                return index
        return None

    def clear(self) -> None:
        if self.marks:
            self.checkpoint()
            self.marks.clear()

    def delete(self, index: int | None) -> None:
        self.delete_many([] if index is None else [index])

    def delete_many(self, indices) -> None:
        valid = {i for i in indices if 0 <= i < len(self.marks)}
        if valid:
            self.checkpoint()
            self.marks = [mark for i, mark in enumerate(self.marks) if i not in valid]

    def copy(self, index: int | None) -> bool:
        return self.copy_many([] if index is None else [index])

    def copy_many(self, indices) -> bool:
        valid = sorted({i for i in indices if 0 <= i < len(self.marks)})
        if not valid:
            return False
        self.clipboard = [deepcopy(self.marks[i]) for i in valid]
        return True

    def paste(self) -> int | None:
        indices = self.paste_many()
        return min(indices) if indices else None

    def paste_many(self) -> set[int]:
        if not self.clipboard:
            return set()
        self.checkpoint()
        start = len(self.marks)
        pasted = [mark.moved(24, 24) for mark in self.clipboard]
        self.marks.extend(pasted)
        self.clipboard = deepcopy(pasted)
        return set(range(start, len(self.marks)))
